
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/lclabpmj/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R dist $DEPLOYPATH
    - /bin/cp -R font $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R mp3 $DEPLOYPATH
